version: '3'

services:
  bot:
    image: python:3.10-alpine3.17
    build: 
      dockerfile: C:\coding\python\telegram_bot\Dockerfile
      context: .
    restart: always
    depends_on:
      - postgres
      - pgadmin

  postgres:
    container_name: postgres
    image: postgres:12.0-alpine
    environment:
      - HOST=${HOST}
      - POSTGRES_DB=${DATABASE}
      - POSTGRES_USER=${USER}
      - PASSWORD=${PASSWORD} 
    ports:
      - "5432:5432"
    volumes:
      - ./database/create.sql:/docker-entrypoint-initdb.d/database-seed.sql
      - ./database/db:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "16543:80"
    volumes:
      - ./database/pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres 
      
    
  


    
